#CAMPOS FORMS
NOMBRE = 1
NOMBRE_COMPLETO = 2
NOMBRE_COMPLETO_DNI = 3
NOMBRES_COMPLETOS_TODOS = 4
NOMBRES_COMPLETOS_TODOS_DNI = 5
DNI = 6
PRIMER_APELLIDO = 7
SEGUNDO_APELLIDO = 8
APELLIDOS = 9
NUM_ENTRADAS = 10
CORREO = 11
INSTAGRAM = 12
TELEFONO = 13
CONDICIONES = 14

#STORIES
NO_STORIES = 15
STORIES_VISTAS = 16
STORIES_NO_VISTAS = 17

#ERROR
ERROR = -1